package br.mil.controlemunicao;

import br.mil.controlemunicao.dto.DevolucaoForm;
import br.mil.controlemunicao.entity.*;
import br.mil.controlemunicao.exception.*;
import br.mil.controlemunicao.repository.*;
import br.mil.controlemunicao.service.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.UUID;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class MovimentacaoServiceTest {
    @Autowired MovimentacaoService service;
    @Autowired DevolucaoService devolucaoService;
    @Autowired EstoquePaiolRepository estoqueRepository;
    @Autowired DevolucaoRepository devolucaoRepository;
    @Autowired ItemDevolucaoRepository itemDevolucaoRepository;
    @Autowired MovimentacaoEstoqueRepository historicoRepository;
    @Autowired LoteMunicaoRepository loteRepository;
    @Autowired MunicaoRepository municaoRepository;
    @Autowired RelatorioAnualPdfService relatorio;
    @Autowired MovimentacaoRepository movimentacaoRepository;
    @Autowired RegistroEntregaEfetivaRepository registroEntregaRepository;
    EstoquePaiol estoque;

    @BeforeEach void preparar() { estoque = estoqueRepository.findAll().get(0); estoque.setQuantidadeAtual(1000); estoque.setQuantidadeReservada(0); estoqueRepository.saveAndFlush(estoque); }

    @Test void solicitacaoReservaSemBaixarFisicoEReduzDisponivel() { Movimentacao m = solicitar(600); EstoquePaiol e = recarregar(); assertEquals(1000,e.getQuantidadeAtual()); assertEquals(600,e.getQuantidadeReservada()); assertEquals(400,e.getQuantidadeDisponivel()); assertEquals(600,service.itens(m.getId()).get(0).getQuantidadeReservada()); }
    @Test void segundaSolicitacaoRespeitaSaldoDisponivel() { solicitar(600); solicitar(300); EstoquePaiol e=recarregar(); assertEquals(900,e.getQuantidadeReservada()); assertEquals(100,e.getQuantidadeDisponivel()); }
    @Test void solicitacaoSemSaldoEhBloqueadaERollbackaReserva() { solicitar(900); assertThrows(EstoqueInsuficienteException.class,()->solicitar(200)); assertEquals(900,recarregar().getQuantidadeReservada()); }
    @Test void cancelamentoLiberaReservaSemAlterarFisico() { Movimentacao m=solicitar(300); service.cancelar(m.getId()); EstoquePaiol e=recarregar(); assertEquals(1000,e.getQuantidadeAtual()); assertEquals(0,e.getQuantidadeReservada()); assertEquals(StatusMovimentacao.CANCELADA,service.buscarPorId(m.getId()).getStatus()); }
    @Test void exclusaoSolicitadaLiberaReservaERemoveRegistro() { Movimentacao m=solicitar(300);Long id=m.getId();service.excluir(id,null);assertFalse(movimentacaoRepository.existsById(id));assertEquals(0,recarregar().getQuantidadeReservada()); }
    @Test void exclusaoComEtapaVinculadaEhBloqueada() { Movimentacao m=solicitar(10);service.autorizar(m.getId(),null);BusinessException erro=assertThrows(BusinessException.class,()->service.excluir(m.getId(),null));assertTrue(erro.getMessage().contains("etapas vinculadas"));assertTrue(movimentacaoRepository.existsById(m.getId())); }
    @Test void aumentarReservaUsaSomenteDiferenca() { Movimentacao m=solicitar(100); service.alterarQuantidadeSolicitada(m.getId(),130,null); assertEquals(130,recarregar().getQuantidadeReservada()); }
    @Test void reduzirReservaLiberaSomenteDiferenca() { Movimentacao m=solicitar(100); service.alterarQuantidadeSolicitada(m.getId(),70,null); assertEquals(70,recarregar().getQuantidadeReservada()); }
    @Test void separacaoNaoBaixaEstoque() { Movimentacao m=solicitar(200); service.autorizar(m.getId(),null); service.confirmarSeparacao(m.getId(),null); EstoquePaiol e=recarregar(); assertEquals(1000,e.getQuantidadeAtual()); assertEquals(200,e.getQuantidadeReservada()); }
    @Test void entregaBaixaFisicoEConsomeReserva() { Movimentacao m=ateTransporte(200); service.confirmarEntrega(m.getId(),200,null,null); EstoquePaiol e=recarregar(); assertEquals(800,e.getQuantidadeAtual()); assertEquals(0,e.getQuantidadeReservada()); }
    @Test void entregaParcialLiberaDiferenca() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),80,"20 não entregues",null); EstoquePaiol e=recarregar(); assertEquals(920,e.getQuantidadeAtual()); assertEquals(0,e.getQuantidadeReservada()); }
    @Test void entregaParcialExigeJustificativa() { Movimentacao m=ateTransporte(100); assertThrows(BusinessException.class,()->service.confirmarEntrega(m.getId(),80,"",null)); assertEquals(1000,recarregar().getQuantidadeAtual()); }
    @Test void entregaRepetidaNaoBaixaDuasVezes() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),100,null,null); assertThrows(BusinessException.class,()->service.confirmarEntrega(m.getId(),100,null,null)); assertEquals(900,recarregar().getQuantidadeAtual()); }
    @Test void entregaSemDivergenciaRegistraLoteOriginalEQuantidadeEfetiva() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),100,null,null); ItemMovimentacao item=service.itens(m.getId()).get(0); RegistroEntregaEfetiva registro=registroEntregaRepository.findByItemMovimentacaoMovimentacaoIdOrderById(m.getId()).get(0); assertEquals(item.getId(),registro.getItemMovimentacao().getId()); assertEquals(item.getLoteMunicao().getId(),registro.getLoteMunicao().getId()); assertEquals(100,registro.getQuantidadeEfetiva()); assertEquals(100,registro.getQuantidadeReservada()); assertEquals(100,registro.getQuantidadeSeparada()); assertEquals(100,item.getQuantidadeSolicitada()); }
    @Test void entregaComQuantidadeZeroPreservaItemOriginalERegistraJustificativa() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),0,"Lote previsto não informado na entrega",null); ItemMovimentacao item=service.itens(m.getId()).get(0); RegistroEntregaEfetiva registro=registroEntregaRepository.findByItemMovimentacaoMovimentacaoIdOrderById(m.getId()).get(0); assertEquals(item.getLoteMunicao().getId(),registro.getLoteMunicao().getId()); assertEquals(0,registro.getQuantidadeEfetiva()); assertEquals("Lote previsto não informado na entrega",registro.getJustificativa()); assertEquals(100,item.getQuantidadeSolicitada()); }
    @Test void entregaComLoteDiferenteCriaRegistroSemSubstituirItemOriginal() { Movimentacao m=ateTransporte(100); EstoquePaiol outro=novoEstoque("EFETIVO","V2",100); ItemMovimentacao item=service.itens(m.getId()).get(0); LoteMunicao loteOriginal=item.getLoteMunicao(); service.confirmarEntregaItens(m.getId(),List.of(item.getId(),item.getId()),List.of(0,100),List.of(loteOriginal.getId(),outro.getLoteMunicao().getId()),"Lote efetivamente informado diferente do previsto",null); item=service.itens(m.getId()).get(0); var registros=registroEntregaRepository.findByItemMovimentacaoMovimentacaoIdOrderById(m.getId()); assertEquals(2,registros.size()); assertEquals(loteOriginal.getId(),item.getLoteMunicao().getId()); assertEquals(loteOriginal.getId(),registros.get(0).getLoteMunicao().getId()); assertEquals(outro.getLoteMunicao().getId(),registros.get(1).getLoteMunicao().getId()); assertEquals("Lote efetivamente informado diferente do previsto",registros.get(1).getJustificativa()); }
    @Test void divergenciaSemJustificativaEhBloqueadaSemPersistirRegistro() { Movimentacao m=ateTransporte(100); EstoquePaiol outro=novoEstoque("SEM-JUSTIFICATIVA","V2",100); ItemMovimentacao item=service.itens(m.getId()).get(0); assertThrows(BusinessException.class,()->service.confirmarEntregaItens(m.getId(),List.of(item.getId(),item.getId()),List.of(0,100),List.of(item.getLoteMunicao().getId(),outro.getLoteMunicao().getId()),null,null)); assertTrue(registroEntregaRepository.findByItemMovimentacaoMovimentacaoIdOrderById(m.getId()).isEmpty()); }
    @Test void quantidadeEfetivaNegativaEhBloqueadaSemPersistirRegistro() { Movimentacao m=ateTransporte(100); ItemMovimentacao item=service.itens(m.getId()).get(0); assertThrows(BusinessException.class,()->service.confirmarEntregaItens(m.getId(),List.of(item.getId()),List.of(-1),List.of(item.getLoteMunicao().getId()),null,null)); assertTrue(registroEntregaRepository.findByItemMovimentacaoMovimentacaoIdOrderById(m.getId()).isEmpty()); }
    @Test void devolucaoPositivaRepoeEstoque() { Movimentacao m=ateTransporte(200); service.confirmarEntrega(m.getId(),200,null,null); devolver(m,100,100,0,null); assertEquals(900,recarregar().getQuantidadeAtual()); }
    @Test void devolucaoZeroNaoAlteraEstoque() { Movimentacao m=ateTransporte(200); service.confirmarEntrega(m.getId(),200,null,null); devolver(m,200,0,0,null); assertEquals(800,recarregar().getQuantidadeAtual()); }
    @Test void devolucaoComCampoUnicoRepoeNoEstoqueRelacionado() { Movimentacao m=ateTransporte(200); service.confirmarEntrega(m.getId(),200,null,null); Devolucao d=devolucaoRepository.findByMovimentacaoId(m.getId()).orElseThrow(); Long item=itemDevolucaoRepository.findByDevolucaoId(d.getId()).get(0).getId(); devolucaoService.registrarQuantidades(d.getId(),List.of(item),List.of(75),null,null,null,null,null); assertEquals(875,recarregar().getQuantidadeAtual()); }
    @Test void solicitacaoAceitaMaisDeUmMaterial() { EstoquePaiol outro=novoEstoque("LT-OUTRO","VR-OUTRA",500);Movimentacao m=novaMovimentacao("MULTI");service.criarSolicitacaoComItens(m,List.of(estoque.getId(),outro.getId()),List.of(100,150),null);assertEquals(2,service.itens(m.getId()).size());assertEquals(100,recarregar().getQuantidadeReservada());assertEquals(150,estoqueRepository.findById(outro.getId()).orElseThrow().getQuantidadeReservada()); }
    @Test void formularioIncompletoNaoEhPersistido() { long antes=movimentacaoRepository.count();Movimentacao m=new Movimentacao();m.setDiex("INCOMPLETA");m.setPaiolOrigem(estoque.getPaiol());BusinessException erro=assertThrows(BusinessException.class,()->service.criarSolicitacao(m,estoque.getId(),10,null));assertTrue(erro.getMessage().contains("Data da retirada"));assertEquals(antes,movimentacaoRepository.count()); }
    @Test void aceiteIncompletoInformaTodosOsCamposPendentes() { Movimentacao m=new Movimentacao();m.setDiex("ACEITE-INCOMPLETO");m.setStatus(StatusMovimentacao.SOLICITADA);m=movimentacaoRepository.saveAndFlush(m);Long id=m.getId();BusinessException erro=assertThrows(BusinessException.class,()->service.autorizar(id,null));assertTrue(erro.getMessage().contains("Data da retirada"));assertTrue(erro.getMessage().contains("Itens da movimentação"));assertEquals(StatusMovimentacao.SOLICITADA,movimentacaoRepository.findById(id).orElseThrow().getStatus()); }
    @Test void combinacaoDuplicadaEhRejeitada() { Movimentacao m=novaMovimentacao("DUP"); assertThrows(BusinessException.class,()->service.criarSolicitacaoComItens(m,List.of(estoque.getId(),estoque.getId()),List.of(10,20),null)); assertEquals(0,recarregar().getQuantidadeReservada()); }
    @Test void edicaoRemoveItemELiberaReserva() { EstoquePaiol outro=novoEstoque("REM","VR-R",100);Movimentacao m=novaMovimentacao("EDIT");service.criarSolicitacaoComItens(m,List.of(estoque.getId(),outro.getId()),List.of(40,30),null);var manter=service.itens(m.getId()).get(0);service.atualizarItens(m.getId(),m,List.of(manter.getId()),List.of(estoque.getId()),List.of(50),null);assertEquals(1,service.itens(m.getId()).size());assertEquals(50,recarregar().getQuantidadeReservada());assertEquals(0,estoqueRepository.findById(outro.getId()).orElseThrow().getQuantidadeReservada()); }
    @Test void edicaoSemAlterarQuantidadeNaoGravaHistoricoZero() { Movimentacao m=solicitar(40);var item=service.itens(m.getId()).get(0);long historicos=historicoRepository.findByMovimentacaoId(m.getId()).size();service.atualizarItens(m.getId(),m,List.of(item.getId()),List.of(estoque.getId()),List.of(40),null);assertEquals(historicos,historicoRepository.findByMovimentacaoId(m.getId()).size());assertEquals(40,recarregar().getQuantidadeReservada()); }
    @Test void movimentacaoFinalizadaNaoPermiteEditarItens() { Movimentacao m=ateTransporte(10);service.confirmarEntrega(m.getId(),10,null,null);Devolucao d=devolucaoRepository.findByMovimentacaoId(m.getId()).orElseThrow();Long item=itemDevolucaoRepository.findByDevolucaoId(d.getId()).get(0).getId();devolucaoService.registrarQuantidades(d.getId(),List.of(item),List.of(0),null,null,null,null,null);assertThrows(BusinessException.class,()->service.atualizarItens(m.getId(),m,List.of(service.itens(m.getId()).get(0).getId()),List.of(estoque.getId()),List.of(10),null)); }
    @Test void campoEbEhOpcionalESalvo() {Movimentacao vazio=solicitar(1);assertNull(vazio.getEb());Movimentacao com=novaMovimentacao("EB");com.setEb("EB-2026-001");service.criarSolicitacao(com,estoque.getId(),1,null);assertEquals("EB-2026-001",service.buscarPorId(com.getId()).getEb());}
    @Test void fluxoTresItensDevolveAosEstoquesCorretosEPdfContemEb() throws Exception {EstoquePaiol b=novoEstoqueOutraMunicao("5,56 mm","LT-015","VR-25",600),c=novoEstoqueOutraMunicao("7,62 mm","LT-021","VR-30",300);Movimentacao m=novaMovimentacao("123/2026");m.setEb("EB-2026-001");m.setMotivoRetirada("Motivo de teste do relatório");m.setObservacao("Observação separada");service.criarSolicitacaoComItens(m,List.of(estoque.getId(),b.getId(),c.getId()),List.of(100,500,200),null);service.autorizar(m.getId(),null);service.confirmarSeparacao(m.getId(),null);service.despachar(m.getId(),null);var mi=service.itens(m.getId());service.confirmarEntregaItens(m.getId(),mi.stream().map(ItemMovimentacao::getId).toList(),List.of(100,500,200),null,null);Devolucao d=devolucaoRepository.findByMovimentacaoId(m.getId()).orElseThrow();var di=itemDevolucaoRepository.findByDevolucaoId(d.getId());devolucaoService.registrarQuantidades(d.getId(),di.stream().map(ItemDevolucao::getId).toList(),List.of(10,0,30),null,null,null,null,null);assertEquals(910,recarregar().getQuantidadeAtual());assertEquals(100,estoqueRepository.findById(b.getId()).orElseThrow().getQuantidadeAtual());assertEquals(130,estoqueRepository.findById(c.getId()).orElseThrow().getQuantidadeAtual());assertEquals(2,historicoRepository.findByMovimentacaoId(m.getId()).stream().filter(h->h.getTipo()==TipoMovimentacaoEstoque.DEVOLUCAO).count());byte[] pdf=relatorio.gerar(LocalDate.now().getYear());var leitor=new com.lowagie.text.pdf.PdfReader(pdf);StringBuilder textoBuilder=new StringBuilder();for(int pagina=1;pagina<=leitor.getNumberOfPages();pagina++)textoBuilder.append(new com.lowagie.text.pdf.parser.PdfTextExtractor(leitor).getTextFromPage(pagina));String texto=textoBuilder.toString();assertTrue(texto.contains("EB-2026-001"),"EB");assertTrue(texto.contains("Motivo da Movimentação: Motivo de teste do relatório"),"motivo");assertTrue(texto.contains("Gerado em: "+LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"))),"gerado");assertTrue(texto.contains("VR-25"),"VR25");assertTrue(texto.contains("VR-30"),"VR30");assertTrue(texto.contains("Efetiva"),"tabela de conciliação");    assertTrue(texto.contains("Diverg"),"coluna de divergência");assertTrue(texto.contains("Observação: Observação separada"),"observacao");assertFalse(texto.contains("Responsáveis:"),"responsaveis");assertFalse(texto.contains("Escolta:"),"escolta");assertFalse(texto.contains("Motoristas:"),"motoristas");}
    @Test void devolucaoRepetidaEhIdempotente() { Movimentacao m=ateTransporte(200); service.confirmarEntrega(m.getId(),200,null,null); Devolucao d=devolver(m,100,100,0,null); var item=itemDevolucaoRepository.findByDevolucaoId(d.getId()).get(0); assertThrows(BusinessException.class,()->devolucaoService.registrar(d.getId(),new DevolucaoForm(item.getId(),100,100,0,null,null),null,null,null,null)); assertEquals(900,recarregar().getQuantidadeAtual()); }
    @Test void devolucaoNegativaOuMaiorQueEntregaEhBloqueada() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),100,null,null); Devolucao d=devolucaoRepository.findByMovimentacaoId(m.getId()).orElseThrow(); Long item=itemDevolucaoRepository.findByDevolucaoId(d.getId()).get(0).getId(); assertThrows(BusinessException.class,()->devolucaoService.registrar(d.getId(),new DevolucaoForm(item,0,-1,0,"x",null),null,null,null,null)); assertThrows(BusinessException.class,()->devolucaoService.registrar(d.getId(),new DevolucaoForm(item,0,101,0,"x",null),null,null,null,null)); }
    @Test void historicoRegistraReservaSaidaLiberacaoEDevolucao() { Movimentacao m=ateTransporte(100); service.confirmarEntrega(m.getId(),80,"parcial",null); devolver(m,40,40,0,null); var tipos=historicoRepository.findByMovimentacaoId(m.getId()).stream().map(MovimentacaoEstoque::getTipo).toList(); assertTrue(tipos.contains(TipoMovimentacaoEstoque.RESERVA)); assertTrue(tipos.contains(TipoMovimentacaoEstoque.SAIDA)); assertTrue(tipos.contains(TipoMovimentacaoEstoque.LIBERACAO_RESERVA)); assertTrue(tipos.contains(TipoMovimentacaoEstoque.DEVOLUCAO)); }
    @Test void executaCenarioFuncionalCompleto() { Movimentacao a=solicitar(600); Movimentacao b=solicitar(300); assertEquals(100,recarregar().getQuantidadeDisponivel()); assertThrows(EstoqueInsuficienteException.class,()->solicitar(200)); service.cancelar(b.getId()); assertEquals(400,recarregar().getQuantidadeDisponivel()); service.autorizar(a.getId(),null); service.confirmarSeparacao(a.getId(),null); service.despachar(a.getId(),null); service.confirmarEntrega(a.getId(),550,"50 não entregues",null); assertEquals(450,recarregar().getQuantidadeAtual()); assertEquals(0,recarregar().getQuantidadeReservada()); devolver(a,450,100,0,null); assertEquals(550,recarregar().getQuantidadeAtual()); assertEquals(550,recarregar().getQuantidadeDisponivel()); }

    private Movimentacao solicitar(int q) { Movimentacao m=new Movimentacao(); m.setDiex("DIEX-"+UUID.randomUUID()); m.setDataSolicitacao(LocalDate.now()); m.setDataApanha(LocalDate.now().plusDays(1)); m.setPaiolOrigem(estoque.getPaiol()); return service.criarSolicitacao(m,estoque.getId(),q,null); }
    private Movimentacao ateTransporte(int q) { Movimentacao m=solicitar(q); service.autorizar(m.getId(),null); service.confirmarSeparacao(m.getId(),null); return service.despachar(m.getId(),null); }
    private EstoquePaiol recarregar() { estoqueRepository.flush(); return estoqueRepository.findById(estoque.getId()).orElseThrow(); }
    private Devolucao devolver(Movimentacao m,int consumida,int devolvida,int estojos,String justificativa) { Devolucao d=devolucaoRepository.findByMovimentacaoId(m.getId()).orElseThrow(); Long item=itemDevolucaoRepository.findByDevolucaoId(d.getId()).get(0).getId(); return devolucaoService.registrar(d.getId(),new DevolucaoForm(item,consumida,devolvida,estojos,justificativa,null),null,null,null,null); }
    private Movimentacao novaMovimentacao(String diex){Movimentacao m=new Movimentacao();m.setDiex(diex);m.setDataSolicitacao(LocalDate.now());m.setDataApanha(LocalDate.now().plusDays(1));m.setPaiolOrigem(estoque.getPaiol());m.setOmSolicitante(estoque.getPaiol().getOrganizacaoMilitar());return m;}
    private EstoquePaiol novoEstoque(String loteNome,String virola,int saldo){LoteMunicao base=estoque.getLoteMunicao();LoteMunicao l=new LoteMunicao();l.setMunicao(base.getMunicao());l.setLote(loteNome+UUID.randomUUID());l.setVirola(virola);l.setDataValidade(LocalDate.now().plusYears(2));l.setOrganizacaoProprietaria(base.getOrganizacaoProprietaria());l.setAtivo(true);l=loteRepository.save(l);EstoquePaiol e=new EstoquePaiol();e.setPaiol(estoque.getPaiol());e.setLoteMunicao(l);e.setQuantidadeAtual(saldo);e.setQuantidadeReservada(0);e.setDataEntrada(java.time.LocalDateTime.now());e.setUltimaMovimentacao(java.time.LocalDateTime.now());return estoqueRepository.save(e);}
    private EstoquePaiol novoEstoqueOutraMunicao(String calibre,String lote,String virola,int saldo){Municao base=estoque.getLoteMunicao().getMunicao();Municao m=new Municao();m.setTipoMunicao(base.getTipoMunicao());m.setCalibre(calibre+UUID.randomUUID());m.setDescricao("Teste");m.setFabricante("Teste");m.setAtivo(true);m=municaoRepository.save(m);LoteMunicao l=new LoteMunicao();l.setMunicao(m);l.setLote(lote+UUID.randomUUID());l.setVirola(virola);l.setDataValidade(LocalDate.now().plusYears(2));l.setOrganizacaoProprietaria(estoque.getLoteMunicao().getOrganizacaoProprietaria());l.setAtivo(true);l=loteRepository.save(l);EstoquePaiol e=new EstoquePaiol();e.setPaiol(estoque.getPaiol());e.setLoteMunicao(l);e.setQuantidadeAtual(saldo);e.setQuantidadeReservada(0);e.setDataEntrada(java.time.LocalDateTime.now());e.setUltimaMovimentacao(java.time.LocalDateTime.now());return estoqueRepository.save(e);}
}
