CREATE TABLE registro_entrega_efetiva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    item_movimentacao_id BIGINT NOT NULL REFERENCES item_movimentacao(id),
    lote_municao_id BIGINT NOT NULL REFERENCES lote_municao(id),
    quantidade_efetiva INTEGER NOT NULL CHECK(quantidade_efetiva >= 0),
    quantidade_reservada INTEGER NOT NULL CHECK(quantidade_reservada >= 0),
    quantidade_separada INTEGER NOT NULL CHECK(quantidade_separada >= 0),
    justificativa VARCHAR(500),
    usuario_responsavel_id BIGINT REFERENCES usuario(id)
);

CREATE INDEX idx_registro_entrega_efetiva_item
    ON registro_entrega_efetiva(item_movimentacao_id);
